# This is a basic workflow to help you get started with Actions

name: common-ci
run-name: Common CI

# Controls when the workflow will run
on:
  # Allows you to call this workflow
  workflow_call:
    inputs:
      workflow_ref:
        description: 'Reference to Composite Action Workflow'
        required: true
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from the common pr workflow

      - name: List directory
        run: ls -lrt
        
  build:
    name: build
    uses: ${{ inputs.workflow_ref }}
